# Generated by Django 3.1.6 on 2021-02-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Netflix_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('creation_date', models.DateField()),
                ('renewal_date', models.DateField()),
                ('is_active', models.BooleanField()),
                ('card', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.card')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netflix_account', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('netflix_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.netflix_account')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='netflix_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.netflix_account'),
        ),
    ]
