# Generated by Django 3.1.6 on 2021-02-26 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210226_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='netflix_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.netflix_account'),
        ),
    ]
