# Generated by Django 3.1.6 on 2021-03-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210226_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
