# Generated by Django 3.1.6 on 2021-03-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210304_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='netflix_account',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
