# Generated by Django 3.1.6 on 2021-03-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210305_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='netflix_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.netflix_account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.card'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='netflix_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.netflix_account'),
        ),
        migrations.AlterField(
            model_name='income',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='income',
            name='netflix_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.netflix_account'),
        ),
        migrations.AlterField(
            model_name='netflix_account',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.card'),
        ),
    ]
